server:
  port : 8084
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/proyectoFinal
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: rabbit-mq

queue:
  serie:
    name: serieQueue

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/